# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: robot_messages.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14robot_messages.proto\"\xc7\x02\n\nSensorData\x12\x10\n\x08sequence\x18\x01 \x01(\r\x12\x11\n\ttimestamp\x18\x02 \x01(\x02\x12\x1c\n\x03imu\x18\x03 \x01(\x0b\x32\x0f.SensorData.IMU\x12\x1c\n\x03gps\x18\x04 \x01(\x0b\x32\x0f.SensorData.GPS\x1a\x92\x01\n\x03IMU\x12\x0f\n\x07\x61\x63\x63\x65l_x\x18\x01 \x01(\x02\x12\x0f\n\x07\x61\x63\x63\x65l_y\x18\x02 \x01(\x02\x12\x0f\n\x07\x61\x63\x63\x65l_z\x18\x03 \x01(\x02\x12\x0e\n\x06gyro_x\x18\x04 \x01(\x02\x12\x0e\n\x06gyro_y\x18\x05 \x01(\x02\x12\x0e\n\x06gyro_z\x18\x06 \x01(\x02\x12\x0c\n\x04roll\x18\x07 \x01(\x02\x12\r\n\x05pitch\x18\x08 \x01(\x02\x12\x0b\n\x03yaw\x18\t \x01(\x02\x1a\x43\n\x03GPS\x12\x0b\n\x03lat\x18\x01 \x01(\x02\x12\x0b\n\x03lon\x18\x02 \x01(\x02\x12\x0b\n\x03\x61lt\x18\x03 \x01(\x02\x12\x15\n\rgps_timestamp\x18\x04 \x01(\x02\"V\n\x0bRobotStatus\x12\x10\n\x08sequence\x18\x01 \x01(\r\x12\x10\n\x08steering\x18\x02 \x01(\x02\x12\x10\n\x08throttle\x18\x03 \x01(\x02\x12\x11\n\ttimestamp\x18\x04 \x01(\x02\"-\n\x07\x43ommand\x12\x10\n\x08steering\x18\x01 \x01(\x02\x12\x10\n\x08throttle\x18\x02 \x01(\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_messages_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SENSORDATA._serialized_start=25
  _SENSORDATA._serialized_end=352
  _SENSORDATA_IMU._serialized_start=137
  _SENSORDATA_IMU._serialized_end=283
  _SENSORDATA_GPS._serialized_start=285
  _SENSORDATA_GPS._serialized_end=352
  _ROBOTSTATUS._serialized_start=354
  _ROBOTSTATUS._serialized_end=440
  _COMMAND._serialized_start=442
  _COMMAND._serialized_end=487
# @@protoc_insertion_point(module_scope)
